### ISSUE TITLE
getRepeatingBitstrings() "true" precedence issue

### ISSUE THREAD

**Issue by llrastegar** [llrastegar/Cube#3]
It seems that if both a "false" and "true" bitstring are found in a file in the same iteration, the algorithm in the for loop does not check out the last possible success for a "false" bitstring in the previous iteration, checking only the bitstring with true at the end and leaving the false at the end of the other trailing behind because it is not read in `b = bits[i]`. This is an issue in File.h.

**Comment by alexbohm** [comment]
there is no "true" precedence
