### ISSUE TITLE
Output binary fails when binary.size() % 8 != 0

### ISSUE THREAD

**Issue by alexbohm** [llrastegar/Cube#4]
We need to add a binary length field to file header along with fields for ids and values.
The header would need to be read by the constructor and written by close().

**Comment by llrastegar** [comment]
I guess the best I can do now is suggest something--add `8 - binary.size()%8` bits to the file (usually done using 0s) and then in the header of the file have the first three bits read while decompressing represent this amount. You only need 3 bits for this, but it may be hard to concatenate this with a character.

**Comment by alexbohm** [comment]
the writing of extra bits is mostly resolved, but the header stuff still needs to be written

**Comment by alexbohm** [comment]
The header for the extra bits is written and appears to work
